info:
  contact: {}
paths:
  /admin/category-add:
    post:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: parent_id
        in: formData
        name: parent_id
        type: integer
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 创建分类
      tags:
      - 管理员方法
  /admin/category-delete:
    delete:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 删除分类
      tags:
      - 管理员方法
  /admin/category-list:
    get:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 获取分类列表
      tags:
      - 管理员方法
  /admin/category-update:
    put:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: name
        in: formData
        name: name
        type: string
      - description: parent_id
        in: formData
        name: parent_id
        type: integer
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 更新分类
      tags:
      - 管理员方法
  /admin/problem-add:
    post:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: title
        in: formData
        name: title
        required: true
        type: string
      - description: content
        in: formData
        name: content
        required: true
        type: string
      - description: max_runtime
        in: formData
        name: max_runtime
        required: true
        type: string
      - description: max_mem
        in: formData
        name: max_mem
        required: true
        type: string
      - collectionFormat: multi
        description: category_ids
        in: formData
        items:
          type: string
        name: category_ids
        required: true
        type: array
      - collectionFormat: multi
        description: test_cases
        in: formData
        items:
          type: string
        name: test_cases
        required: true
        type: array
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 创建问题
      tags:
      - 管理员方法
  /admin/problem-update:
    put:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: title
        in: formData
        name: title
        required: true
        type: string
      - description: content
        in: formData
        name: content
        required: true
        type: string
      - description: max_runtime
        in: formData
        name: max_runtime
        required: true
        type: integer
      - description: max_mem
        in: formData
        name: max_mem
        required: true
        type: integer
      - collectionFormat: multi
        description: category_ids
        in: formData
        items:
          type: string
        name: category_ids
        type: array
      - collectionFormat: multi
        description: test_cases
        in: formData
        items:
          type: string
        name: test_cases
        type: array
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 更新问题
      tags:
      - 管理员方法
  /login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共的方法
  /problem-detail:
    get:
      parameters:
      - description: identity
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 获取问题详情
      tags:
      - 公共的方法
  /problem-list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: category_identity
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 获取问题列表
      tags:
      - 公共的方法
  /rank-list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 获取排行榜列表
      tags:
      - 公共的方法
  /register:
    post:
      parameters:
      - description: email
        in: formData
        name: email
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: phone
        in: formData
        name: phone
        type: string
      - description: code
        in: formData
        name: code
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共的方法
  /submit-list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: problem_identity
        in: query
        name: problem_identity
        type: string
      - description: user_identity
        in: query
        name: user_identity
        type: string
      - description: status
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 获取提交列表
      tags:
      - 公共的方法
  /user-detail:
    get:
      parameters:
      - description: identity
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 获取用户详情
      tags:
      - 公共的方法
  /user/submit:
    post:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: problem_identity
        in: query
        name: problem_identity
        required: true
        type: string
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 提交代码
      tags:
      - 用户的方法
  /verify-code:
    post:
      parameters:
      - description: email
        in: formData
        name: email
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200", "msg":"", "data":""}'
          schema:
            type: string
      summary: 获取验证码
      tags:
      - 公共的方法
swagger: "2.0"
